const GHSMUN_KEY = 'ghsmun-content-v1';
const supabaseReady = window.SUPABASE_URL && window.SUPABASE_ANON_KEY && !window.SUPABASE_URL.includes('YOUR_') && window.supabase;
const db = supabaseReady ? window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY) : null;
const qmark = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"%3E%3Crect width="800" height="500" fill="%2374000e"/%3E%3Ctext x="400" y="350" text-anchor="middle" font-family="Georgia" font-size="390" font-weight="bold" fill="%23fff"%3E?%3C/text%3E%3C/svg%3E';
const defaults = {
  home:{eyebrow:'Greenwich High School · Model United Nations',title:'Global voices.',accent:'Local leaders.',lede:'A community of students learning to think deeply, speak confidently, and work together on the questions that shape our world.',heroImage:'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=2000&q=85'},
  about:{title:'Diplomacy starts here.',description:'GHSMUN is a student-led Model United Nations club at Greenwich High School. We believe the best leaders are people who research deeply, communicate clearly, and seek common ground across difference.',groupImage:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=2000&q=85'},
  conference:{season:'October 2026',location:'Greenwich High School',registration:'Opening soon'},
  profiles:[
    {name:'Name',role:'Secretary-General',grade:'Grade',contact:'email@example.com',image:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80'},
    {name:'Name',role:'Director-General',grade:'Grade',contact:'email@example.com',image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80'},
    {name:'Name',role:'Chief of Staff',grade:'Grade',contact:'email@example.com',image:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80'},
    {name:'Name',role:'USG of Committees',grade:'Grade',contact:'email@example.com',image:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80'},
    {name:'Name',role:'USG of Operations',grade:'Grade',contact:'email@example.com',image:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80'}
  ],
  committees:[
    {category:'GENERAL ASSEMBLY',name:'United Nations Development Programme',topic:'Topic to be announced',description:'Develop ambitious, practical responses to inequality, sustainability, and human development across the globe.',image:'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1000&q=85',guide:'#'},
    {category:'GENERAL ASSEMBLY',name:'World Health Organization',topic:'Topic to be announced',description:'Bring evidence, empathy, and diplomacy to pressing questions of health and equity.',image:'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1000&q=85',guide:'#'},
    {category:'SPECIALIZED',name:'Apollo 13 Mission',topic:'Topic to be announced',description:'Step into mission control and make the decisions that will determine whether the crew makes it home.',image:'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?auto=format&fit=crop&w=1000&q=85',guide:'#'},
    {category:'SPECIALIZED',name:'Council of Greek Gods',topic:'Topic to be announced',description:'Navigate divine rivalries, mortal consequences, and the fate of Olympus in this mythic council.',image:'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1000&q=85',guide:'#'},
    {category:'CRISIS',name:'Historical Crisis: The Future of Arabia',topic:'Topic to be announced',description:'Shape the future of a changing region through strategy, alliances, and rapid-fire directives.',image:'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1000&q=85',guide:'#'},
    {category:'CRISIS',name:'Ad Hoc Committee',topic:'A surprise awaits',description:'No brief, no spoilers—just a room full of sharp minds ready for anything.',image:qmark,guide:'#'}
  ]
};
let data = structuredClone(defaults);
const esc = (value='') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const imageStyle = (url) => `style="--profile-image:url('${esc(url)}');--committee-image:url('${esc(url)}');--dialog-image:url('${esc(url)}')"`;
const nav = (active) => `<div class="notice">GREENWICH HIGH SCHOOL MODEL UNITED NATIONS</div><nav class="site-nav wrap" aria-label="Main navigation"><a class="brand" href="index.html"><span class="logo-box"><img src="assets/ChatGPT_Image_Sep_9__2026__09_59_27_PM-removebg-preview.png" alt="" width="72" height="72"></span>GHSMUN</a><div class="nav-links" id="main-nav-links"><a class="${active==='home'?'active':''}" href="index.html">Home</a><a class="${active==='conference'?'active':''}" href="conference.html">Conference</a><a class="${active==='about'?'active':''}" href="about.html">About Us</a><a class="contact" href="mailto:ghsgovernmunt@gmail.com">Contact</a><button type="button" class="admin-trigger" data-admin-launch>Admin</button></div><button type="button" class="menu-toggle" aria-label="Open navigation menu" aria-expanded="false" aria-controls="main-nav-links"><span></span><span></span><span></span></button></nav>`;
const footer = () => `<footer class="site-footer"><div class="wrap"><div class="footer-top"><div><p class="eyebrow" style="color:var(--gold)">GHSMUN</p><h2>Diplomacy starts here.</h2></div><a href="mailto:ghsgovernmunt@gmail.com">ghsgovernmunt@gmail.com</a></div><div class="footer-bottom">© 2026 GHSMUN · GREENWICH HIGH SCHOOL (BACKEND DESIGNED BY <span style = "color: white"> <a href = "https://www.github.com/willzlog"><u>ALBIN ZIEME</u></a></span>) </div></div></footer>`;

function renderHome(root){root.innerHTML = `${nav('home')}<main class="home-dynamic"><section class="hero" style="--hero-image:url('${esc(data.home.heroImage)}')"><div class="hero-content wrap"><p class="eyebrow">${esc(data.home.eyebrow)}</p><h1>${esc(data.home.title)}<br><em>${esc(data.home.accent)}</em></h1><p class="lede">${esc(data.home.lede)}</p><a class="button" href="conference.html">Explore GHSMUN 2026 →</a><div class="stats"><div class="stat"><b>100+</b><span>Members</span></div><div class="stat"><b>${esc(data.conference.season)}</b><span>Next conference</span></div><div class="stat"><b>∞</b><span>Perspectives</span></div></div></div></section><section class="section wrap"><div class="section-heading"><p class="eyebrow">The GHSMUN experience</p><h2>Learn to see the whole world.</h2><p class="section-copy">Model UN is a place to research, debate, and discover what becomes possible when people with different perspectives work toward a shared solution.</p></div><div class="feature-grid"><div class="photo" style="--photo:url('https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=85')"></div><div><p class="eyebrow">Built for every delegate</p><h3>Find your seat at the table.</h3><p>Whether you are giving your first speech or leading a committee, GHSMUN offers the preparation, encouragement, and room to grow.</p><a class="link-arrow" href="about.html">Meet our community →</a></div></div></section></main>${footer()}`;}
function renderAbout(root){const cards=data.profiles.map((p,i)=>`<article class="profile"><div class="profile-photo" ${imageStyle(p.image)}></div><div class="profile-copy"><h3>${esc(p.name)}</h3><p class="role">${esc(p.role)}</p><dl><dt>Grade: </dt><dd>${esc(p.grade)}</dd><br><dt>Contact: </dt><dd>${esc(p.contact)}</dd></dl></div></article>`).join('');root.innerHTML=`${nav('about')}<main><section class="hero-group" style="--group-image:url('${esc(data.about.groupImage)}')"><div class="wrap"><p class="eyebrow">About GHSMUN</p><h1>${esc(data.about.title)}</h1><p>${esc(data.about.description)}</p></div></section><section class="section governmun"><div class="wrap"><div class="governmun-head"><div><p class="eyebrow">Our leadership</p><h2>Our GovernMUNt</h2><p class="section-copy">Meet the student team behind GHSMUN.</p></div><div class="carousel-controls"><button data-carousel="prev" aria-label="Previous leaders">←</button><button data-carousel="next" aria-label="Next leaders">→</button></div></div><div class="profile-carousel" data-carousel-track>${cards}</div></div></section></main>${footer()}`;}
function renderConference(root){const cards=data.committees.map((c,i)=>`<article class="committee"><div class="committee-image" ${imageStyle(c.image)}></div><span class="number">${String(i+1).padStart(2,'0')} / ${esc(c.category)}</span><h3>${esc(c.name)}</h3><p class="topic">${esc(c.topic)}</p><p>${esc(c.description)}</p><a href="#" data-committee="${i}">Committee details →</a></article>`).join('');root.innerHTML=`${nav('conference')}<main><header class="page-title"><div class="wrap"><p class="eyebrow">Our annual conference</p><h1>GHSMUN 2026</h1><p>A welcoming, high-energy day of diplomacy for new and experienced delegates alike.</p></div></header><section class="section wrap conference-intro"><div class="photo" style="--photo:url('https://images.unsplash.com/photo-1569012871812-f38ee64cd54c?auto=format&fit=crop&w=1200&q=85')"></div><div><p class="eyebrow">Save the date</p><h2>One day. A world of possibilities.</h2><div class="details"><div><span>When</span><b>${esc(data.conference.season)}</b></div><div><span>Where</span><b>${esc(data.conference.location)}</b></div><div><span>Registration</span><b>${esc(data.conference.registration)}</b></div></div></div></section><section class="section band"><div class="wrap"><p class="eyebrow">Committees</p><h2>Choose your room.</h2><p class="section-copy">Select a committee for its topic, background, guide, and a closer look at what awaits.</p><div class="committee-grid">${cards}</div></div></section></main>${footer()}`;}
function openCommittee(index){const c=data.committees[index], dialog=document.createElement('dialog');dialog.className='committee-dialog';dialog.innerHTML=`<div class="dialog-image" ${imageStyle(c.image)}></div><div class="dialog-copy"><button class="dialog-close" aria-label="Close">×</button><p class="eyebrow">${esc(c.category)}</p><h2>${esc(c.name)}</h2><p class="topic"><strong>Topic:</strong> ${esc(c.topic)}</p><p>${esc(c.description)}</p><a class="guide-button" href="${esc(c.guide)}" target="_blank" rel="noopener">Open background guide →</a></div>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>dialog.remove());}
function field(label,name,value,area=false){return `<label class="admin-field">${label}${area?`<textarea name="${name}">${esc(value)}</textarea>`:`<input name="${name}" value="${esc(value)}">`}</label>`;}
async function openAdmin(){if(!db){const login=document.createElement('dialog');login.className='login-card';login.innerHTML=`<button class="dialog-close" aria-label="Close">×</button><h2>Supabase setup needed</h2><p>Add the project URL and publishable key to <b>supabase-config.js</b> before using the admin page.</p>`;document.body.append(login);login.showModal();login.querySelector('.dialog-close').onclick=()=>login.close();login.addEventListener('close',()=>login.remove());return}const {data:{session}}=await db.auth.getSession();if(session){openEditor();return}const login=document.createElement('dialog');login.className='login-card';login.innerHTML=`<button class="dialog-close" aria-label="Close">×</button><h2>GHSMUN admin</h2><p>Sign in to edit the site.</p><form><input type="email" name="email" autocomplete="username" autofocus placeholder="Email" required><input type="password" name="password" autocomplete="current-password" placeholder="Password" required><p class="login-error"></p><button class="button">Continue →</button></form>`;document.body.append(login);login.showModal();login.querySelector('.dialog-close').onclick=()=>login.close();login.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=login.querySelector('.button'),errorText=login.querySelector('.login-error'),form=new FormData(e.currentTarget);button.disabled=true;errorText.textContent='';const {error}=await db.auth.signInWithPassword({email:form.get('email'),password:form.get('password')});button.disabled=false;if(error){errorText.textContent='That email or password is not correct.';return}login.close();openEditor()};login.addEventListener('close',()=>login.remove());}
function openEditor(){
  const dialog=document.createElement('dialog');
  dialog.className='admin-dialog';
  const profileForms=data.profiles.map((p,i)=>`<div class="admin-item"><div class="admin-item-top"><b>Person ${i+1}</b><button type="button" class="remove-item" data-remove-profile="${i}">Remove</button></div><div class="admin-grid">${field('Name',`p-name-${i}`,p.name)}${field('Role',`p-role-${i}`,p.role)}${field('Grade',`p-grade-${i}`,p.grade)}${field('Contact',`p-contact-${i}`,p.contact)}<div style="grid-column:1/-1">${field('Photo URL',`p-image-${i}`,p.image)}</div></div></div>`).join('');
  const committeeForms=data.committees.map((c,i)=>`<div class="admin-item"><div class="admin-item-top"><b>Committee ${i+1}</b><button type="button" class="remove-item" data-remove-committee="${i}">Remove</button></div><div class="admin-grid">${field('Category',`c-category-${i}`,c.category)}${field('Committee name',`c-name-${i}`,c.name)}${field('Topic',`c-topic-${i}`,c.topic)}${field('Background-guide link',`c-guide-${i}`,c.guide)}<div style="grid-column:1/-1">${field('Description',`c-description-${i}`,c.description,true)}</div><div style="grid-column:1/-1">${field('Image URL',`c-image-${i}`,c.image)}</div></div></div>`).join('');
  dialog.innerHTML=`<div class="admin-header"><h2>Edit GHSMUN</h2><button type="button" class="admin-logout">Sign out</button><button class="admin-close" aria-label="Close">×</button></div><form class="admin-form"><section class="admin-section"><h3>Home page</h3><div class="admin-grid">${field('Eyebrow','home-eyebrow',data.home.eyebrow)}${field('Hero image URL','home-image',data.home.heroImage)}<div style="grid-column:1/-1">${field('Main title','home-title',data.home.title)}</div><div style="grid-column:1/-1">${field('Accent title','home-accent',data.home.accent)}</div><div style="grid-column:1/-1">${field('Introduction','home-lede',data.home.lede,true)}</div></div></section><section class="admin-section"><h3>About page</h3><div class="admin-grid">${field('About title','about-title',data.about.title)}${field('Group photo URL','about-image',data.about.groupImage)}<div style="grid-column:1/-1">${field('About description','about-description',data.about.description,true)}</div></div></section><section class="admin-section"><h3>Conference details</h3><div class="admin-grid">${field('Date / season','conference-season',data.conference.season)}${field('Location','conference-location',data.conference.location)}${field('Registration status','conference-registration',data.conference.registration)}</div></section><section class="admin-section"><h3>GovernMUNt profiles</h3>${profileForms}<button type="button" class="add-item" data-add-profile>Add a person</button></section><section class="admin-section"><h3>Committee widgets</h3>${committeeForms}<button type="button" class="add-item" data-add-committee>Add a committee</button></section><button class="save-admin">Save changes</button></form>`;
  document.body.append(dialog);
  dialog.showModal();
  dialog.querySelector('.admin-close').onclick=()=>dialog.close();
  dialog.querySelector('.admin-logout').onclick=async()=>{await db.auth.signOut();dialog.close()};
  dialog.addEventListener('close',()=>dialog.remove());
  dialog.querySelector('[data-add-profile]').onclick=()=>{data.profiles.push({name:'Name',role:'Role',grade:'Grade',contact:'email@example.com',image:''});dialog.close();openEditor()};
  dialog.querySelector('[data-add-committee]').onclick=()=>{data.committees.push({category:'CATEGORY',name:'New committee',topic:'Topic to be announced',description:'Add a description.',image:'',guide:'#'});dialog.close();openEditor()};
  dialog.querySelectorAll('[data-remove-profile]').forEach(b=>b.onclick=()=>{data.profiles.splice(+b.dataset.removeProfile,1);dialog.close();openEditor()});
  dialog.querySelectorAll('[data-remove-committee]').forEach(b=>b.onclick=()=>{data.committees.splice(+b.dataset.removeCommittee,1);dialog.close();openEditor()});
  dialog.querySelector('form').onsubmit=e=>{e.preventDefault();saveAdminForm(e.currentTarget,dialog)};
}
async function saveAdminForm(form,dialog){const f=new FormData(form),get=n=>f.get(n)||'',button=form.querySelector('.save-admin');data.home={eyebrow:get('home-eyebrow'),heroImage:get('home-image'),title:get('home-title'),accent:get('home-accent'),lede:get('home-lede')};data.about={title:get('about-title'),groupImage:get('about-image'),description:get('about-description')};data.conference={season:get('conference-season'),location:get('conference-location'),registration:get('conference-registration')};data.profiles=data.profiles.map((p,i)=>({name:get(`p-name-${i}`),role:get(`p-role-${i}`),grade:get(`p-grade-${i}`),contact:get(`p-contact-${i}`),image:get(`p-image-${i}`)}));data.committees=data.committees.map((c,i)=>({category:get(`c-category-${i}`),name:get(`c-name-${i}`),topic:get(`c-topic-${i}`),description:get(`c-description-${i}`),image:get(`c-image-${i}`),guide:get(`c-guide-${i}`)}));button.disabled=true;button.textContent='Saving...';const {error}=await db.from('site_content').upsert({id:'main',content:data,updated_at:new Date().toISOString()});if(error){button.disabled=false;button.textContent='Could not save. Try again.';return}localStorage.removeItem(GHSMUN_KEY);dialog.close();render()}
async function loadContent(){const saved=JSON.parse(localStorage.getItem(GHSMUN_KEY)||'null');if(!db){data=saved||structuredClone(defaults);render();return}const {data:row,error}=await db.from('site_content').select('content').eq('id','main').maybeSingle();data=!error&&row?.content?row.content:saved||structuredClone(defaults);render()}
function bindNavigation(root) {
  const navigation = root.querySelector('.site-nav');
  const toggle = navigation.querySelector('.menu-toggle');
  const links = navigation.querySelector('.nav-links');
  const setOpen = (open) => {
    navigation.classList.toggle('nav-open', open);
    toggle.setAttribute('aria-expanded', String(open));
    toggle.setAttribute('aria-label', open ? 'Close navigation menu' : 'Open navigation menu');
  };
  toggle.addEventListener('click', () => setOpen(toggle.getAttribute('aria-expanded') !== 'true'));
  links.addEventListener('click', (event) => {
    if (event.target.closest('a, button')) {
      if (event.target.closest('[data-admin-launch]') && toggle.getClientRects().length) toggle.focus();
      setOpen(false);
    }
  });
  navigation.addEventListener('keydown', (event) => {
    if (event.key === 'Escape' && toggle.getAttribute('aria-expanded') === 'true') {
      setOpen(false);
      toggle.focus();
    }
  });
  navigation.addEventListener('focusout', (event) => {
    if (!navigation.contains(event.relatedTarget)) setOpen(false);
  });
}
function bind(root){bindNavigation(root);root.querySelector('[data-admin-launch]')?.addEventListener('click',openAdmin);root.querySelectorAll('[data-committee]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();openCommittee(+link.dataset.committee)}));const track=root.querySelector('[data-carousel-track]');root.querySelector('[data-carousel="prev"]')?.addEventListener('click',()=>track.scrollBy({left:-track.clientWidth*.86,behavior:'smooth'}));root.querySelector('[data-carousel="next"]')?.addEventListener('click',()=>track.scrollBy({left:track.clientWidth*.86,behavior:'smooth'}));}
function render(){const root=document.querySelector('#site-root'),page=root.dataset.page;if(page==='home')renderHome(root);if(page==='about')renderAbout(root);if(page==='conference')renderConference(root);bind(root)}
document.addEventListener('DOMContentLoaded',loadContent);
